### ISSUE TITLE
How is this repo related to LEGO?

### ISSUE THREAD

**Issue by dolmen** [LEGO/nc3ctf2022-bricketeers#1]
How is this repository related to LEGO?

**Comment by Nicoolai** [comment]
Hi @dolmen 
This is a repo showing the write-ups of a [CTF](https://en.wikipedia.org/wiki/Capture_the_flag_(cybersecurity)) some of us did.
It is good practice to share the writeup afterwards, this is what this repo holds.
We're pretty serious about software security and competitions like this is a fun way to practice some of that.

BUT,  you have a great point, I will add some details about the purpose, in the readme.

Feel free to reopen (or just comment) if you have more questions!
